# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ShapeCreator import creator_execute, CircleCreator, SquareCreator
from AbstractShapeCreator import abstract_draw_circle, abstract_draw_square, BlueFactory, BlackFactory
from Builder import House1_Builder, House2_Builder, Director


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Square = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Square.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.pushButton_Square.setObjectName("pushButton_Square")
        self.pushButton_Circle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Circle.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.pushButton_Circle.setObjectName("pushButton_Circle")
        self.label_Factory = QtWidgets.QLabel(self.centralwidget)
        self.label_Factory.setGeometry(QtCore.QRect(30, 10, 47, 13))
        self.label_Factory.setObjectName("label_Factory")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 250, 641, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 100, 1061, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_AbstractFactory = QtWidgets.QLabel(self.centralwidget)
        self.label_AbstractFactory.setGeometry(QtCore.QRect(30, 120, 81, 16))
        self.label_AbstractFactory.setObjectName("label_AbstractFactory")
        self.label_BlueFactory = QtWidgets.QLabel(self.centralwidget)
        self.label_BlueFactory.setGeometry(QtCore.QRect(40, 140, 71, 16))
        self.label_BlueFactory.setObjectName("label_BlueFactory")
        self.label_BlackFactory = QtWidgets.QLabel(self.centralwidget)
        self.label_BlackFactory.setGeometry(QtCore.QRect(40, 190, 71, 16))
        self.label_BlackFactory.setObjectName("label_BlackFactory")
        self.pushButton_BlueSquare = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BlueSquare.setGeometry(QtCore.QRect(50, 160, 75, 23))
        self.pushButton_BlueSquare.setObjectName("pushButton_BlueSquare")
        self.pushButton_BlueCircle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BlueCircle.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.pushButton_BlueCircle.setObjectName("pushButton_BlueCircle")
        self.pushButton_BlackSquare = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BlackSquare.setGeometry(QtCore.QRect(50, 210, 75, 23))
        self.pushButton_BlackSquare.setObjectName("pushButton_BlackSquare")
        self.pushButton_BlackCircle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BlackCircle.setGeometry(QtCore.QRect(130, 210, 75, 23))
        self.pushButton_BlackCircle.setObjectName("pushButton_BlackCircle")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(110, -10, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_Builder = QtWidgets.QLabel(self.centralwidget)
        self.label_Builder.setGeometry(QtCore.QRect(170, 10, 47, 13))
        self.label_Builder.setObjectName("label_Builder")
        self.pushButton_House1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_House1.setGeometry(QtCore.QRect(150, 40, 75, 23))
        self.pushButton_House1.setObjectName("pushButton_House1")
        self.pushButton_House2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_House2.setGeometry(QtCore.QRect(150, 70, 75, 23))
        self.pushButton_House2.setObjectName("pushButton_House2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.scene = QtWidgets.QGraphicsScene()
        self.graphicsView.setScene(self.scene)

        self.pushButton_Circle.clicked.connect(self.circle_click)
        self.pushButton_Square.clicked.connect(self.square_click)
        self.pushButton_BlueSquare.clicked.connect(self.blue_square_click)
        self.pushButton_BlueCircle.clicked.connect(self.blue_circle_click)
        self.pushButton_BlackSquare.clicked.connect(self.black_square_click)
        self.pushButton_BlackCircle.clicked.connect(self.black_circle_click)
        self.pushButton_House1.clicked.connect(self.build_house1)
        self.pushButton_House2.clicked.connect(self.build_house2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Square.setText(_translate("MainWindow", "Square"))
        self.pushButton_Circle.setText(_translate("MainWindow", "Circle"))
        self.label_Factory.setText(_translate("MainWindow", "Factory"))
        self.label_AbstractFactory.setText(_translate("MainWindow", "Abstract Factory"))
        self.label_BlueFactory.setText(_translate("MainWindow", "Blue Factory"))
        self.label_BlackFactory.setText(_translate("MainWindow", "Black Factory"))
        self.pushButton_BlueSquare.setText(_translate("MainWindow", "Square"))
        self.pushButton_BlueCircle.setText(_translate("MainWindow", "Circle"))
        self.pushButton_BlackSquare.setText(_translate("MainWindow", "Square"))
        self.pushButton_BlackCircle.setText(_translate("MainWindow", "Circle"))
        self.label_Builder.setText(_translate("MainWindow", "Builder"))
        self.pushButton_House1.setText(_translate("MainWindow", "House 1"))
        self.pushButton_House2.setText(_translate("MainWindow", "House 2"))

    def circle_click(self):
        self.scene.clear()
        creator_execute(CircleCreator(), self)

    def square_click(self):
        self.scene.clear()
        creator_execute(SquareCreator(), self)

    def blue_square_click(self):
        self.scene.clear()
        abstract_draw_square(BlueFactory(), self)

    def black_square_click(self):
        self.scene.clear()
        abstract_draw_square(BlackFactory(), self)

    def blue_circle_click(self):
        self.scene.clear()
        abstract_draw_circle(BlueFactory(), self)

    def black_circle_click(self):
        self.scene.clear()
        abstract_draw_circle(BlackFactory(), self)

    def draw_ui(self, item):
        self.scene.addItem(item)

    def build_house1(self):
        self.scene.clear()
        director = Director()
        builder = House1_Builder()
        director.builder = builder
        director.build_full_house()
        builder.house.build_house(self)

    def build_house2(self):
        self.scene.clear()
        director = Director()
        builder = House2_Builder()
        director.builder = builder
        director.build_full_house()
        builder.house.build_house(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
